trunk/nephron-backend/nephron-web/src/main/java/eu/nephron/view/user/RoleBean.java
package eu.nephron.view.user;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import eu.nephron.controller.user.RoleService;
import eu.nephron.model.role.Role;

@ManagedBean(name="roleBean")
@SessionScoped
public class RoleBean {
	
	@EJB
	private RoleService roleService;
	
	public List<Role> getAllRoles() {
		return roleService.findAllRoles();
	}
	
}

trunk/nephron-backend/nephron-web/src/main/java/eu/nephron/view/user/UserBean.java
package eu.nephron.view.user;

import javax.ejb.EJB;
import javax.enterprise.inject.Produces;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import eu.nephron.controller.user.UserService;
import eu.nephron.model.user.NephronUser;

@ManagedBean(name="userBean")
@SessionScoped
public class UserBean {
	
	private static final String LOGGED_IN = "loggedIn";
	
	@EJB
	private UserService userService;
	
	private NephronUser user;
	
	private String userName;
	
	private String password;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

    public String login() {
    	user = userService.findUserByUserNameAndPassword(userName, password);
    	return LOGGED_IN;
    }

    public void logout() {
        user = null;
    }
    
    public boolean isLoggedIn() {
       return null != user;
    }
    
    @Produces
    @LoggedIn 
    public NephronUser getCurrentUser() {
        return user;
    }
	
}

trunk/nephron-backend/nephron-web/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:body>

	<ui:composition template="resources/components/templates/layout.xhtml">

		<ui:define name="navigation">
			<h:form>
				<h:panelGrid>
					<h:link value="Login" outcome="resources/components/login" />
				</h:panelGrid>
			</h:form>
		</ui:define>

		<ui:define name="content" align="center">

			<p>
				<b>Welcome to NEPHRON+</b>
			</p>
			NEPHRON+ will provide a major leap forward in Renal Care:<br />
			<ul>
				<li>It is a next generation, integrated solution for
					personalized treatment and management of patients with chronic
					renal failure.</li>
				<li>It presents an ideal solution for continuous dialysis
					outside the hospital offering better blood clearance, while
					patients can stay mobile and active in social and economic life.</li>
				<li>It relies on an ICT-enabled wearable artificial kidney for
					on-body blood purification.</li>
			</ul>
		</ui:define>

		<ui:define name="calendar" />

	</ui:composition>

</h:body>

</html>

trunk/nephron-backend/nephron-web/src/main/webapp/resources/components/role/display.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:body>

	<ui:composition template="../templates/layout.xhtml">

		<ui:define name="navigation">
			<h:panelGrid>
				<h:link>Schedule</h:link>
			</h:panelGrid>
		</ui:define>

		<ui:define name="content">

			<h:dataTable value="#{roleBean.allRoles}" var="role">
				<h:column>
					<f:facet name="header">Role ID</f:facet>
    				#{role.id}
	    		</h:column>
				<h:column>
					<f:facet name="header">Name</f:facet>
    				#{role.name}
	    		</h:column>
				<h:column>
					<f:facet name="header">Code</f:facet>
    				#{role.code}
	    		</h:column>
				<h:column>
					<f:facet name="header">Status</f:facet>
    				#{role.status}
	    		</h:column>
				<h:column>
					<f:facet name="header">Effective Date</f:facet>
    				#{role.effectiveDate}
	    		</h:column>
			</h:dataTable>

			<h:link>Add</h:link> | <h:link>Edit</h:link> | <h:link>Delete</h:link>

		</ui:define>

		<ui:define name="calendar" />

	</ui:composition>

</h:body>

</html>