trunk/nephron-BackendSOAP/Nephron-DB-Data/src/java/eu/nephron/model/entity/Device.java
package eu.nephron.model.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@DiscriminatorValue("1")
@NamedQueries({
	@NamedQuery(name="Device.findWakdBySerialNumber",
		query="select d from Device d where d.role.code='WAKD' and d.serialNumber=:serialNumber"),
	@NamedQuery(name="Device.findSmartPhoneBySerialNumber",
		query="select d from Device d where d.role.code='SP' and d.serialNumber=:serialNumber")
//	@NamedQuery(name="Device.findWakdByCommandID", 
//		query="select d from CommandAct ca, Participation p, Device d where ca.id=:commandID and ca.actStatus=1 and ca.moodCode=4 and p.act.id=ca.id and p.medicalEntity.id=d.id and d.role.code='WAKD'"),
//	@NamedQuery(name="Device.findAssociatedDevice", 
//		query="select d2 from AssociationAct a, Participation p1, Participation p2, Device d1, Device d2 where p1.act.id=a.id and p2.act.id=a.id and p1.medicalEntity.id=d1.id and p2.medicalEntity.id=d2.id and d1.id<>d2.id and d1.id=:deviceID")
})
public class Device extends MedicalEntity {

	private static final long serialVersionUID = 744885745424571530L;

	@Column(name="SERIAL_NUMBER", unique=true)
	private String serialNumber;
	
	@Column(name="EXPIRATION_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date expirationDate;
	
	@Column(name="MANUFACTURED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date manufacturedDate;

	public String getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public Date getExpirationDate() {
		return expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public Date getManufacturedDate() {
		return manufacturedDate;
	}

	public void setManufacturedDate(Date manufacturedDate) {
		this.manufacturedDate = manufacturedDate;
	}
	
}

trunk/nephron-BackendSOAP/Nephron-DB-Data/src/java/enterprise/web_jpa_war/servlet/DeviceController.java
package enterprise.web_jpa_war.servlet;

import eu.nephron.model.entity.Device;
import enterprise.web_jpa_war.servlet.util.JsfUtil;
import enterprise.web_jpa_war.servlet.util.PaginationHelper;
import eu.nephron.beans.DeviceFacade;


import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "deviceController")
@SessionScoped
public class DeviceController implements Serializable {

    private Device current;
    private DataModel items = null;
    @EJB
    private DeviceFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public DeviceController() {
    }

    public Device getSelected() {
        if (current == null) {
            current = new Device();
            selectedItemIndex = -1;
        }
        return current;
    }

    private DeviceFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Device) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Device();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DeviceCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Device) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DeviceUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Device) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DeviceDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Device.class)
    public static class DeviceControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DeviceController controller = (DeviceController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "deviceController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Device) {
                Device o = (Device) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Device.class.getName());
            }
        }
    }
}

trunk/nephron-BackendSOAP/Nephron-DB-Data/web/device/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateDeviceTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_serialNumber}" for="serialNumber" />
                    <h:inputText id="serialNumber" value="#{deviceController.selected.serialNumber}" title="#{bundle.CreateDeviceTitle_serialNumber}" />
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_expirationDate}" for="expirationDate" />
                    <h:inputText id="expirationDate" value="#{deviceController.selected.expirationDate}" title="#{bundle.CreateDeviceTitle_expirationDate}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_manufacturedDate}" for="manufacturedDate" />
                    <h:inputText id="manufacturedDate" value="#{deviceController.selected.manufacturedDate}" title="#{bundle.CreateDeviceTitle_manufacturedDate}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_id}" for="id" />
                    <h:inputText id="id" value="#{deviceController.selected.id}" title="#{bundle.CreateDeviceTitle_id}" />
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_code}" for="code" />
                    <h:inputText id="code" value="#{deviceController.selected.code}" title="#{bundle.CreateDeviceTitle_code}" />
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_name}" for="name" />
                    <h:inputText id="name" value="#{deviceController.selected.name}" title="#{bundle.CreateDeviceTitle_name}" required="true" requiredMessage="#{bundle.CreateDeviceRequiredMessage_name}"/>
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_quantity}" for="quantity" />
                    <h:inputText id="quantity" value="#{deviceController.selected.quantity}" title="#{bundle.CreateDeviceTitle_quantity}" />
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_effectiveDate}" for="effectiveDate" />
                    <h:inputText id="effectiveDate" value="#{deviceController.selected.effectiveDate}" title="#{bundle.CreateDeviceTitle_effectiveDate}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateDeviceLabel_role}" for="role" />
                    <h:selectOneMenu id="role" value="#{deviceController.selected.role}" title="#{bundle.CreateDeviceTitle_role}" required="true" requiredMessage="#{bundle.CreateDeviceRequiredMessage_role}">
                        <f:selectItems value="#{roleController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{deviceController.create}" value="#{bundle.CreateDeviceSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{deviceController.prepareList}" value="#{bundle.CreateDeviceShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateDeviceIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

trunk/nephron-BackendSOAP/Nephron-DB-Data/web/device/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditDeviceTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditDeviceLabel_serialNumber}" for="serialNumber" />
                    <h:inputText id="serialNumber" value="#{deviceController.selected.serialNumber}" title="#{bundle.EditDeviceTitle_serialNumber}" />
                    <h:outputLabel value="#{bundle.EditDeviceLabel_expirationDate}" for="expirationDate" />
                    <h:inputText id="expirationDate" value="#{deviceController.selected.expirationDate}" title="#{bundle.EditDeviceTitle_expirationDate}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditDeviceLabel_manufacturedDate}" for="manufacturedDate" />
                    <h:inputText id="manufacturedDate" value="#{deviceController.selected.manufacturedDate}" title="#{bundle.EditDeviceTitle_manufacturedDate}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditDeviceLabel_id}" for="id" />
                    <h:inputText id="id" value="#{deviceController.selected.id}" title="#{bundle.EditDeviceTitle_id}" />
                    <h:outputLabel value="#{bundle.EditDeviceLabel_code}" for="code" />
                    <h:inputText id="code" value="#{deviceController.selected.code}" title="#{bundle.EditDeviceTitle_code}" />
                    <h:outputLabel value="#{bundle.EditDeviceLabel_name}" for="name" />
                    <h:inputText id="name" value="#{deviceController.selected.name}" title="#{bundle.EditDeviceTitle_name}" required="true" requiredMessage="#{bundle.EditDeviceRequiredMessage_name}"/>
                    <h:outputLabel value="#{bundle.EditDeviceLabel_quantity}" for="quantity" />
                    <h:inputText id="quantity" value="#{deviceController.selected.quantity}" title="#{bundle.EditDeviceTitle_quantity}" />
                    <h:outputLabel value="#{bundle.EditDeviceLabel_effectiveDate}" for="effectiveDate" />
                    <h:inputText id="effectiveDate" value="#{deviceController.selected.effectiveDate}" title="#{bundle.EditDeviceTitle_effectiveDate}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditDeviceLabel_role}" for="role" />
                    <h:selectOneMenu id="role" value="#{deviceController.selected.role}" title="#{bundle.EditDeviceTitle_role}" required="true" requiredMessage="#{bundle.EditDeviceRequiredMessage_role}">
                        <f:selectItems value="#{roleController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{deviceController.update}" value="#{bundle.EditDeviceSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditDeviceViewLink}"/>
                <br />
                <h:commandLink action="#{deviceController.prepareList}" value="#{bundle.EditDeviceShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditDeviceIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

trunk/nephron-BackendSOAP/Nephron-DB-Data/web/device/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListDeviceTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListDeviceEmpty}" rendered="#{deviceController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{deviceController.items.rowCount > 0}">
                    <h:outputText value="#{deviceController.pagination.pageFirstItem + 1}..#{deviceController.pagination.pageLastItem + 1}/#{deviceController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{deviceController.previous}" value="#{bundle.Previous} #{deviceController.pagination.pageSize}" rendered="#{deviceController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{deviceController.next}" value="#{bundle.Next} #{deviceController.pagination.pageSize}" rendered="#{deviceController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{deviceController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_serialNumber}"/>
                            </f:facet>
                            <h:outputText value="#{item.serialNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_expirationDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.expirationDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_manufacturedDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.manufacturedDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_code}"/>
                            </f:facet>
                            <h:outputText value="#{item.code}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_quantity}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantity}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_effectiveDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.effectiveDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDeviceTitle_role}"/>
                            </f:facet>
                            <h:outputText value="#{item.role}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{deviceController.prepareView}" value="#{bundle.ListDeviceViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{deviceController.prepareEdit}" value="#{bundle.ListDeviceEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{deviceController.destroy}" value="#{bundle.ListDeviceDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{deviceController.prepareCreate}" value="#{bundle.ListDeviceCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListDeviceIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

trunk/nephron-BackendSOAP/Nephron-DB-Data/web/device/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewDeviceTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewDeviceLabel_serialNumber}"/>
                    <h:outputText value="#{deviceController.selected.serialNumber}" title="#{bundle.ViewDeviceTitle_serialNumber}"/>
                    <h:outputText value="#{bundle.ViewDeviceLabel_expirationDate}"/>
                    <h:outputText value="#{deviceController.selected.expirationDate}" title="#{bundle.ViewDeviceTitle_expirationDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewDeviceLabel_manufacturedDate}"/>
                    <h:outputText value="#{deviceController.selected.manufacturedDate}" title="#{bundle.ViewDeviceTitle_manufacturedDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewDeviceLabel_id}"/>
                    <h:outputText value="#{deviceController.selected.id}" title="#{bundle.ViewDeviceTitle_id}"/>
                    <h:outputText value="#{bundle.ViewDeviceLabel_code}"/>
                    <h:outputText value="#{deviceController.selected.code}" title="#{bundle.ViewDeviceTitle_code}"/>
                    <h:outputText value="#{bundle.ViewDeviceLabel_name}"/>
                    <h:outputText value="#{deviceController.selected.name}" title="#{bundle.ViewDeviceTitle_name}"/>
                    <h:outputText value="#{bundle.ViewDeviceLabel_quantity}"/>
                    <h:outputText value="#{deviceController.selected.quantity}" title="#{bundle.ViewDeviceTitle_quantity}"/>
                    <h:outputText value="#{bundle.ViewDeviceLabel_effectiveDate}"/>
                    <h:outputText value="#{deviceController.selected.effectiveDate}" title="#{bundle.ViewDeviceTitle_effectiveDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewDeviceLabel_role}"/>
                    <h:outputText value="#{deviceController.selected.role}" title="#{bundle.ViewDeviceTitle_role}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{deviceController.destroyAndView}" value="#{bundle.ViewDeviceDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewDeviceEditLink}"/>
                <br />
                <h:commandLink action="#{deviceController.prepareCreate}" value="#{bundle.ViewDeviceCreateLink}" />
                <br />
                <h:commandLink action="#{deviceController.prepareList}" value="#{bundle.ViewDeviceShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewDeviceIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>