trunk/nephron-BackendSOAP/PKI-Infastructure/src/java/enterprise/web_jpa_war/entity/patientconnectionsController.java
package enterprise.web_jpa_war.entity;

import eu.nephron.entity.patientconnections;
import enterprise.web_jpa_war.entity.util.JsfUtil;
import enterprise.web_jpa_war.entity.util.PaginationHelper;
import eu.nephron.role.bean.patientconnectionsFacadeLocal;


import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "patientconnectionsController")
@SessionScoped
public class patientconnectionsController implements Serializable {

    private patientconnections current;
    private DataModel items = null;
    @EJB
    private patientconnectionsFacadeLocal ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public patientconnectionsController() {
    }

    public patientconnections getSelected() {
        if (current == null) {
            current = new patientconnections();
            selectedItemIndex = -1;
        }
        return current;
    }

    private patientconnectionsFacadeLocal getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (patientconnections) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new patientconnections();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("patientconnectionsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (patientconnections) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("patientconnectionsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (patientconnections) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("patientconnectionsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = patientconnections.class)
    public static class patientconnectionsControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            patientconnectionsController controller = (patientconnectionsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "patientconnectionsController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof patientconnections) {
                patientconnections o = (patientconnections) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + patientconnections.class.getName());
            }
        }
    }
}

trunk/nephron-BackendSOAP/PKI-Infastructure/src/java/enterprise/web_jpa_war/entity/util/PaginationHelper.java
package enterprise.web_jpa_war.entity.util;

import javax.faces.model.DataModel;

public abstract class PaginationHelper {

    private int pageSize;
    private int page;

    public PaginationHelper(int pageSize) {
        this.pageSize = pageSize;
    }

    public abstract int getItemsCount();

    public abstract DataModel createPageDataModel();

    public int getPageFirstItem() {
        return page * pageSize;
    }

    public int getPageLastItem() {
        int i = getPageFirstItem() + pageSize - 1;
        int count = getItemsCount() - 1;
        if (i > count) {
            i = count;
        }
        if (i < 0) {
            i = 0;
        }
        return i;
    }

    public boolean isHasNextPage() {
        return (page + 1) * pageSize + 1 <= getItemsCount();
    }

    public void nextPage() {
        if (isHasNextPage()) {
            page++;
        }
    }

    public boolean isHasPreviousPage() {
        return page > 0;
    }

    public void previousPage() {
        if (isHasPreviousPage()) {
            page--;
        }
    }

    public int getPageSize() {
        return pageSize;
    }
}

trunk/nephron-BackendSOAP/PKI-Infastructure/src/java/eu/nephron/entity/patientconnections.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.nephron.entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 *
 * @author tdim
 */
@Entity
public class patientconnections implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private Long idcontact;
    private Long idpersonnal;
    private Long idaddress;
    private Long idpatient;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof patientconnections)) {
            return false;
        }
        patientconnections other = (patientconnections) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "eu.nephron.entity.patientconnections[ id=" + id + " ]";
    }

    /**
     * @return the idcontact
     */
    public Long getIdcontact() {
        return idcontact;
    }

    /**
     * @param idcontact the idcontact to set
     */
    public void setIdcontact(Long idcontact) {
        this.idcontact = idcontact;
    }

    /**
     * @return the idpersonnal
     */
    public Long getIdpersonnal() {
        return idpersonnal;
    }

    /**
     * @param idpersonnal the idpersonnal to set
     */
    public void setIdpersonnal(Long idpersonnal) {
        this.idpersonnal = idpersonnal;
    }

    /**
     * @return the idaddress
     */
    public Long getIdaddress() {
        return idaddress;
    }

    /**
     * @param idaddress the idaddress to set
     */
    public void setIdaddress(Long idaddress) {
        this.idaddress = idaddress;
    }

    /**
     * @return the idpatient
     */
    public Long getIdpatient() {
        return idpatient;
    }

    /**
     * @param idpatient the idpatient to set
     */
    public void setIdpatient(Long idpatient) {
        this.idpatient = idpatient;
    }
    
}

trunk/nephron-BackendSOAP/PKI-Infastructure/web/patientconnections/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatepatientconnectionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatepatientconnectionsLabel_id}" for="id" />
                    <h:inputText id="id" value="#{patientconnectionsController.selected.id}" title="#{bundle.CreatepatientconnectionsTitle_id}" />
                    <h:outputLabel value="#{bundle.CreatepatientconnectionsLabel_idcontact}" for="idcontact" />
                    <h:inputText id="idcontact" value="#{patientconnectionsController.selected.idcontact}" title="#{bundle.CreatepatientconnectionsTitle_idcontact}" />
                    <h:outputLabel value="#{bundle.CreatepatientconnectionsLabel_idpersonnal}" for="idpersonnal" />
                    <h:inputText id="idpersonnal" value="#{patientconnectionsController.selected.idpersonnal}" title="#{bundle.CreatepatientconnectionsTitle_idpersonnal}" />
                    <h:outputLabel value="#{bundle.CreatepatientconnectionsLabel_idaddress}" for="idaddress" />
                    <h:inputText id="idaddress" value="#{patientconnectionsController.selected.idaddress}" title="#{bundle.CreatepatientconnectionsTitle_idaddress}" />
                    <h:outputLabel value="#{bundle.CreatepatientconnectionsLabel_idpatient}" for="idpatient" />
                    <h:inputText id="idpatient" value="#{patientconnectionsController.selected.idpatient}" title="#{bundle.CreatepatientconnectionsTitle_idpatient}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{patientconnectionsController.create}" value="#{bundle.CreatepatientconnectionsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{patientconnectionsController.prepareList}" value="#{bundle.CreatepatientconnectionsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreatepatientconnectionsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

trunk/nephron-BackendSOAP/PKI-Infastructure/web/patientconnections/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditpatientconnectionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditpatientconnectionsLabel_id}" for="id" />
                    <h:inputText id="id" value="#{patientconnectionsController.selected.id}" title="#{bundle.EditpatientconnectionsTitle_id}" />
                    <h:outputLabel value="#{bundle.EditpatientconnectionsLabel_idcontact}" for="idcontact" />
                    <h:inputText id="idcontact" value="#{patientconnectionsController.selected.idcontact}" title="#{bundle.EditpatientconnectionsTitle_idcontact}" />
                    <h:outputLabel value="#{bundle.EditpatientconnectionsLabel_idpersonnal}" for="idpersonnal" />
                    <h:inputText id="idpersonnal" value="#{patientconnectionsController.selected.idpersonnal}" title="#{bundle.EditpatientconnectionsTitle_idpersonnal}" />
                    <h:outputLabel value="#{bundle.EditpatientconnectionsLabel_idaddress}" for="idaddress" />
                    <h:inputText id="idaddress" value="#{patientconnectionsController.selected.idaddress}" title="#{bundle.EditpatientconnectionsTitle_idaddress}" />
                    <h:outputLabel value="#{bundle.EditpatientconnectionsLabel_idpatient}" for="idpatient" />
                    <h:inputText id="idpatient" value="#{patientconnectionsController.selected.idpatient}" title="#{bundle.EditpatientconnectionsTitle_idpatient}" />
                </h:panelGrid>
                <h:commandLink action="#{patientconnectionsController.update}" value="#{bundle.EditpatientconnectionsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditpatientconnectionsViewLink}"/>
                <br />
                <h:commandLink action="#{patientconnectionsController.prepareList}" value="#{bundle.EditpatientconnectionsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditpatientconnectionsIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

trunk/nephron-BackendSOAP/PKI-Infastructure/web/patientconnections/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListpatientconnectionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListpatientconnectionsEmpty}" rendered="#{patientconnectionsController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{patientconnectionsController.items.rowCount > 0}">
                    <h:outputText value="#{patientconnectionsController.pagination.pageFirstItem + 1}..#{patientconnectionsController.pagination.pageLastItem + 1}/#{patientconnectionsController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{patientconnectionsController.previous}" value="#{bundle.Previous} #{patientconnectionsController.pagination.pageSize}" rendered="#{patientconnectionsController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{patientconnectionsController.next}" value="#{bundle.Next} #{patientconnectionsController.pagination.pageSize}" rendered="#{patientconnectionsController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{patientconnectionsController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListpatientconnectionsTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListpatientconnectionsTitle_idcontact}"/>
                            </f:facet>
                            <h:outputText value="#{item.idcontact}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListpatientconnectionsTitle_idpersonnal}"/>
                            </f:facet>
                            <h:outputText value="#{item.idpersonnal}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListpatientconnectionsTitle_idaddress}"/>
                            </f:facet>
                            <h:outputText value="#{item.idaddress}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListpatientconnectionsTitle_idpatient}"/>
                            </f:facet>
                            <h:outputText value="#{item.idpatient}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{patientconnectionsController.prepareView}" value="#{bundle.ListpatientconnectionsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{patientconnectionsController.prepareEdit}" value="#{bundle.ListpatientconnectionsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{patientconnectionsController.destroy}" value="#{bundle.ListpatientconnectionsDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{patientconnectionsController.prepareCreate}" value="#{bundle.ListpatientconnectionsCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListpatientconnectionsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

trunk/nephron-BackendSOAP/PKI-Infastructure/web/patientconnections/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewpatientconnectionsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewpatientconnectionsLabel_id}"/>
                    <h:outputText value="#{patientconnectionsController.selected.id}" title="#{bundle.ViewpatientconnectionsTitle_id}"/>
                    <h:outputText value="#{bundle.ViewpatientconnectionsLabel_idcontact}"/>
                    <h:outputText value="#{patientconnectionsController.selected.idcontact}" title="#{bundle.ViewpatientconnectionsTitle_idcontact}"/>
                    <h:outputText value="#{bundle.ViewpatientconnectionsLabel_idpersonnal}"/>
                    <h:outputText value="#{patientconnectionsController.selected.idpersonnal}" title="#{bundle.ViewpatientconnectionsTitle_idpersonnal}"/>
                    <h:outputText value="#{bundle.ViewpatientconnectionsLabel_idaddress}"/>
                    <h:outputText value="#{patientconnectionsController.selected.idaddress}" title="#{bundle.ViewpatientconnectionsTitle_idaddress}"/>
                    <h:outputText value="#{bundle.ViewpatientconnectionsLabel_idpatient}"/>
                    <h:outputText value="#{patientconnectionsController.selected.idpatient}" title="#{bundle.ViewpatientconnectionsTitle_idpatient}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{patientconnectionsController.destroyAndView}" value="#{bundle.ViewpatientconnectionsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewpatientconnectionsEditLink}"/>
                <br />
                <h:commandLink action="#{patientconnectionsController.prepareCreate}" value="#{bundle.ViewpatientconnectionsCreateLink}" />
                <br />
                <h:commandLink action="#{patientconnectionsController.prepareList}" value="#{bundle.ViewpatientconnectionsShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewpatientconnectionsIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>