trunk/Portal/NephronWebPortal/src/java/eu/nephron/dashboard/patient/TableBean.java
package eu.nephron.dashboard.patient;

import eu.nephron.model.Patient;
import eu.nephron.patientsecurityws.SecurePatientConnection;
import eu.nephron.patientsecurityws.SecurePatientConnection_Service;
import eu.nephron.soap.ws.PersonalInfoManager_Service;
import eu.nephron.soap.ws.commandmanager.ActServiceManager_Service;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.faces.context.FacesContext;
import javax.xml.ws.WebServiceRef;

@ManagedBean
@SessionScoped
public class TableBean implements Serializable {

    private List<Patient> filteredPatient;
    private List<Patient> Patients;
    private Patient selectedPatient;
    private Patient[] selectedPatients;
    private String useridforedit;

    public TableBean() {
        Patients = new ArrayList<Patient>();
        populatePatient(Patients);
    }

    private void populatePatient(List<Patient> list) {

        java.util.List<Object> pFind = findConnections(new Long(3), "");

        for (int i = 0; i < pFind.size(); i++) {

            Patient pNew2 = new Patient();
            Patient pdd = findAll((Long) pFind.get(i));
            pNew2.setId((Long) pFind.get(i));
            pNew2.setFatherName(pdd.getFatherName());
            pNew2.setFirstName(pdd.getFirstName());
            pNew2.setLastName(pdd.getLastName());
            list.add(pNew2);
        }
    }

    /**
     * @return the filteredPatient
     */
    public List<Patient> getFilteredPatient() {
        return filteredPatient;
    }

    /**
     * @param filteredPatient the filteredPatient to set
     */
    public void setFilteredPatient(List<Patient> filteredPatient) {
        this.filteredPatient = filteredPatient;
    }

    /**
     * @return the Patients
     */
    public List<Patient> getPatients() {
        return Patients;
    }

    /**
     * @param Patients the Patients to set
     */
    public void setPatients(List<Patient> Patients) {
        this.Patients = Patients;
    }

    /**
     * @return the selectedPatient
     */
    public Patient getSelectedPatient() {
        return selectedPatient;
    }

    /**
     * @param selectedPatient the selectedPatient to set
     */
    public void setSelectedPatient(Patient selectedPatient) {
        this.selectedPatient = selectedPatient;
    }

    /**
     * @return the selectedPatients
     */
    public Patient[] getSelectedPatients() {
        return selectedPatients;
    }

    /**
     * @param selectedPatients the selectedPatients to set
     */
    public void setSelectedPatients(Patient[] selectedPatients) {
        this.selectedPatients = selectedPatients;
    }

    private Patient findAll(Long pID) {
        Patient ppa = new Patient();

        java.util.List<eu.nephron.patientsecurityws.Patientconnections> pfind = findAll_1();
        for (int i = 0; i < pfind.size(); i++) {
            if (pfind.get(i).getIdpatient() == pID) {
                PersonalInfoManager_Service service2 = new PersonalInfoManager_Service();
                eu.nephron.soap.ws.PersonalInfoManager port2 = service2.getPersonalInfoManagerPort();
                java.util.List<eu.nephron.soap.ws.PersonalInfo> pp = port2.findPersonalInfoByID(pfind.get(i).getIdpersonnal());
                ppa.setFirstName(pp.get(0).getFirstName());
                ppa.setLastName(pp.get(0).getLastName());
                ppa.setFatherName(pp.get(0).getFatherName());
            }
        }
        return ppa;
    }

    public String edituser() {
        long ifind = Long.parseLong(getUseridforedit());
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("PUserID", getUseridforedit());
        return "DashBoard_Patient?faces-redirect=true";
    }

    /**
     * @return the useridforedit
     */
    public String getUseridforedit() {
        return useridforedit;
    }

    /**
     * @param useridforedit the useridforedit to set
     */
    public void setUseridforedit(String useridforedit) {
        this.useridforedit = useridforedit;
    }

    private java.util.List<eu.nephron.patientsecurityws.Patientconnections> findAll_1() {
        SecurePatientConnection_Service service = new SecurePatientConnection_Service();
        eu.nephron.patientsecurityws.SecurePatientConnection port = service.getSecurePatientConnectionPort();
        return port.findAllSecurePatientConnection();
    }

    private java.util.List<java.lang.Object> findConnections(java.lang.Long arg0, java.lang.String arg1) {
        System.out.print("Calling WS to find connections");
        ActServiceManager_Service service = new ActServiceManager_Service();
        eu.nephron.soap.ws.commandmanager.ActServiceManager port = service.getActServiceManagerPort();
        return port.findConnections(arg0, arg1);
    }
}

trunk/Portal/NephronWebPortal/web/Alerts.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"

      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Nephron DashBoard</title>
                <link href="wel/template-2012/stylesheets/ec.css" media="all" rel="stylesheet" type="text/css"/>
                <h:outputStylesheet library="css" name="wel/template-2012/stylesheets/ec.css"  />
                <link href="stylesheets/esponder.css" media="all" rel="stylesheet" type="text/css"/>
                <h:outputStylesheet library="css" name="stylesheets/esponder.css"  />
            </f:facet>

            <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript" ></script>

        </h:head>

        <h:body>
            <p:ajaxStatus onstart="statusDialog.show();" onsuccess="statusDialog.hide();"/>  

            <p:dialog modal="true" widgetVar="statusDialog" header="Status"   
                      draggable="false" closable="false">  
                <p:graphicImage value="images/ajax-loader.gif" />  
            </p:dialog>

            <h:form id="form"> 
                <f:metadata>  
                    <f:viewParam name="userID" value="#{tableBean.useridforedit}" />  

                </f:metadata>
                <p:layout fullPage="true">

                    <p:layoutUnit position="north" size="80" resizable="true" closable="true" collapsible="true">
                        <ui:include src="header.xhtml"></ui:include>

                    </p:layoutUnit>

                    <p:layoutUnit position="south" size="40" resizable="false"  closable="false" collapsible="false">
                        <div class="layout-footer"> Copyright @2013 Nephron
                        </div>

                    </p:layoutUnit>

                    <p:layoutUnit position="west" size="175" header="Menu" collapsible="true">
                        <ui:include src="menu.xhtml"></ui:include>

                    </p:layoutUnit>

                    <p:layoutUnit position="center">

                        <p:panel id="panel" header="Alerts Filter" style="margin-bottom:10px;">  
                            <p:panelGrid columns="7">
                                <h:outputLabel for="datefrom" value="Date From : " />
                                <p:calendar value="#{basicApplicationBean.dateFromM}"  id="datefrom" showOn="button" style="width:270px" pattern="MM/dd/yyyy HH:mm"/>
                                <h:outputLabel for="dateto" value="Date To : " />
                                <p:calendar value="#{basicApplicationBean.dateToM}"  id="dateto" showOn="button" style="width:270px" pattern="MM/dd/yyyy HH:mm"/>
                                <p:commandButton value="Refresh" update="panel2234567,alertTable" id="ajax"  
                                                 actionListener="#{basicApplicationBean.UpdateRecords}" styleClass="ui-priority-primary"/>
                            </p:panelGrid>
                        </p:panel>

                        <p:panel id="panel2234567" header="Alerts" style="margin-bottom:10px;"> 
                            <p:dataTable var="patientdss" value="#{basicApplicationBean.sumups2}"  paginator="true" rows="10"  
                                         id="alertTable">  



                                <f:facet name="header">  
                                    WAKD Alerts
                                </f:facet>  

                                <p:column headerText="ID" id="dsspid" style="text-align:center">  
                                    #{patientdss.id}  
                                </p:column>  

                                <p:column headerText="Patient"  id="dsspfname" style="text-align:center">  
                                    #{patientdss.ruleresults}  
                                </p:column>  

                                <p:column headerText="Check"  id="dsspfaname" style="text-align:center">  
                                    #{patientdss.rulename}  
                                </p:column>  

                                <p:column headerText="Message"  id="dssplname" style="text-align:center">  
                                    #{patientdss.ruleresults1}  
                                </p:column>  
                                <p:column headerText="Date"  id="dssplname22Date" style="text-align:center">  
                                    #{patientdss.ruleresults2}  
                                </p:column>  





                            </p:dataTable>  

                        </p:panel> 

                        <h:panelGrid columns="2">  
                            <p:panel header="Export All Data">  
                                <h:commandLink>  
                                    <p:graphicImage value="/images/excel.png" />  
                                    <p:dataExporter type="xls" target="alertTable" fileName="alertTable" />  
                                </h:commandLink>  

                                <h:commandLink>  
                                    <p:graphicImage value="/images/pdf.png" />  
                                    <p:dataExporter type="pdf" target="alertTable" fileName="alertTable"/>  
                                </h:commandLink>  

                                <h:commandLink>  
                                    <p:graphicImage value="/images/csv.png" />  
                                    <p:dataExporter type="csv" target="alertTable" fileName="alertTable" />  
                                </h:commandLink>  

                                <h:commandLink>  
                                    <p:graphicImage value="/images/xml.png" />  
                                    <p:dataExporter type="xml" target="alertTable" fileName="alertTable" />  
                                </h:commandLink>  
                            </p:panel>  

                            <p:panel header="Export Page Data">  
                                <h:commandLink>  
                                    <p:graphicImage value="/images/excel.png" />  
                                    <p:dataExporter type="xls" target="alertTable" fileName="alertTable" pageOnly="true"/>  
                                </h:commandLink>  

                                <h:commandLink>  
                                    <p:graphicImage value="/images/pdf.png" />  
                                    <p:dataExporter type="pdf" target="alertTable" fileName="alertTable" pageOnly="true"/>  
                                </h:commandLink>  

                                <h:commandLink>  
                                    <p:graphicImage value="/images/csv.png" />  
                                    <p:dataExporter type="csv" target="alertTable" fileName="alertTable" pageOnly="true"/>  
                                </h:commandLink>  

                                <h:commandLink>  
                                    <p:graphicImage value="/images/xml.png" />  
                                    <p:dataExporter type="xml" target="alertTable" fileName="alertTable" pageOnly="true"/>  
                                </h:commandLink>  
                            </p:panel>  
                        </h:panelGrid>  

                    </p:layoutUnit>

                </p:layout>
            </h:form>
        </h:body>

    </f:view>
</html>

trunk/Portal/NephronWebPortal/web/DashBoard.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"

      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Nephron DashBoard</title>
                <link href="wel/template-2012/stylesheets/ec.css" media="all" rel="stylesheet" type="text/css"/>
                <h:outputStylesheet library="css" name="wel/template-2012/stylesheets/ec.css"  />
                <link href="stylesheets/esponder.css" media="all" rel="stylesheet" type="text/css"/>
                <h:outputStylesheet library="css" name="stylesheets/esponder.css"  />
            </f:facet>

            <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript" ></script>

        </h:head>

        <h:body>

            <p:ajaxStatus onstart="statusDialog.show();" onsuccess="statusDialog.hide();"/>  

            <p:dialog modal="true" widgetVar="statusDialog" header="Status"   
                      draggable="false" closable="false">  
                <p:graphicImage value="images/ajax-loader.gif" />  
            </p:dialog>


            <h:form id="form"> 
                <f:metadata>  
                    <f:viewParam name="userID" value="#{basicApplicationBean.useridforedit}" />  

                </f:metadata>
                <p:layout fullPage="true">

                    <p:layoutUnit position="north" size="80" resizable="true" closable="true" collapsible="true">
                        <ui:include src="header_d.xhtml"></ui:include>

                    </p:layoutUnit>

                    <p:layoutUnit position="south" size="40" resizable="false"  closable="false" collapsible="false">
                        <div class="layout-footer"> Copyright @2013 Nephron
                        </div>

                    </p:layoutUnit>

                    <p:layoutUnit position="center" align="center">





                        <p:tabView >  

                            <p:tab title="Patients" align="center">  


                                <p:dataTable var="patient" value="#{basicApplicationBean.patients}" rowKey="#{patient.id}" paginator="true" rows="10"  
                                             selection="#{basicApplicationBean.selectedPatient}" selectionMode="single" filteredValue="#{basicApplicationBean.filteredPatient}" id="patientsTable">  



                                    <f:facet name="header">  
                                        List of Patients  
                                    </f:facet>  

                                    <p:column headerText="ID" sortBy="#{patient.id}" filterBy="#{patient.id}" id="pid" style="text-align:center">  
                                        #{patient.id}  
                                    </p:column>  

                                    <p:column headerText="First Name" sortBy="#{patient.firstName}" filterBy="#{patient.firstName}" id="pfname" style="text-align:center">  
                                        #{patient.firstName}  
                                    </p:column>  

                                    <p:column headerText="Fathers Name" sortBy="#{patient.fatherName}" filterBy="#{patient.fatherName}" id="pfathername" style="text-align:center">  
                                        #{patient.fatherName}  
                                    </p:column>  

                                    <p:column headerText="Last Name" sortBy="#{patient.lastName}" filterBy="#{patient.lastName}" id="plname" style="text-align:center">  
                                        #{patient.lastName}  
                                    </p:column>  



                                    <p:column headerText="Actions" >  
                                        <p:commandButton id="editusers" value="View" 
                                                         action="#{basicApplicationBean.edituser()}"

                                                         type="submit"
                                                         >

                                            <f:param name="userID" value="#{patient.id}" />

                                        </p:commandButton>
                                    </p:column>  



                                </p:dataTable>  



                            </p:tab>  

                            <p:tab title="Last 24hr Alerts" align="center">  

                                <p:dataTable var="patientdss" value="#{basicApplicationBean.sumups}"  paginator="true" rows="10"  
                                             id="patientsdssTable">  



                                    <f:facet name="header">  
                                        WAKD Alerts and DSS Alerts  
                                    </f:facet>  

                                    <p:column headerText="ID" id="dsspid" style="text-align:center">  
                                        #{patientdss.id}  
                                    </p:column>  

                                    <p:column headerText="Patient"  id="dsspfname" style="text-align:center">  
                                        #{patientdss.ruleresults}  
                                    </p:column>  

                                    <p:column headerText="Check"  id="dsspfaname" style="text-align:center">  
                                        #{patientdss.rulename}  
                                    </p:column>  

                                    <p:column headerText="Message"  id="dssplname" style="text-align:center">  
                                        #{patientdss.ruleresults1}  
                                    </p:column>  
                                    <p:column headerText="Date"  id="dssplname22Date" style="text-align:center">  
                                        #{patientdss.ruleresults2}  
                                    </p:column>  





                                </p:dataTable>  

                            </p:tab>  


                        </p:tabView>    
                    </p:layoutUnit>

                </p:layout>
            </h:form>
        </h:body>

    </f:view>
</html>

trunk/Portal/NephronWebPortal/web/DashBoard_1.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"

      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Nephron DashBoard</title>
                <link href="wel/template-2012/stylesheets/ec.css" media="all" rel="stylesheet" type="text/css"/>
                <h:outputStylesheet library="css" name="wel/template-2012/stylesheets/ec.css"  />
                <link href="stylesheets/esponder.css" media="all" rel="stylesheet" type="text/css"/>
                <h:outputStylesheet library="css" name="stylesheets/esponder.css"  />
            </f:facet>

            <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript" ></script>

        </h:head>

        <h:body>

            <p:ajaxStatus onstart="statusDialog.show();" onsuccess="statusDialog.hide();"/>  

            <p:dialog modal="true" widgetVar="statusDialog" header="Status"   
                      draggable="false" closable="false">  
                <p:graphicImage value="images/ajax-loader.gif" />  
            </p:dialog>


            <h:form id="form"> 
                <f:metadata>  
                    <f:viewParam name="userID" value="#{tableBean.useridforedit}" />  

                </f:metadata>
                <p:layout fullPage="true">

                    <p:layoutUnit position="north" size="80" resizable="true" closable="true" collapsible="true">
                        <ui:include src="header.xhtml"></ui:include>

                    </p:layoutUnit>

                    <p:layoutUnit position="south" size="40" resizable="false"  closable="false" collapsible="false">
                        <div class="layout-footer"> Copyright @2013 Nephron
                        </div>

                    </p:layoutUnit>

                    <p:layoutUnit position="center" align="center">





                        <p:tabView >  

                            <p:tab title="Summary" align="center">  

                                <p:dataTable var="patientdss" value="#{tableBeanSumup.sumups}"  paginator="true" rows="10"  
                                             id="patientsdssTable">  



                                    <f:facet name="header">  
                                        Summary  
                                    </f:facet>  

                                    <p:column headerText="ID" id="dsspid" style="text-align:center">  
                                        #{patientdss.id}  
                                    </p:column>  

                                    <p:column headerText="Patient"  id="dsspfname" style="text-align:center">  
                                        #{patientdss.ruleresults}  
                                    </p:column>  

                                    <p:column headerText="Check"  id="dsspfaname" style="text-align:center">  
                                        #{patientdss.rulename}  
                                    </p:column>  

                                    <p:column headerText="Message"  id="dssplname" style="text-align:center">  
                                        #{patientdss.ruleresults1}  
                                    </p:column>  
                                    <p:column headerText="Date"  id="dssplname22Date" style="text-align:center">  
                                        #{patientdss.ruleresults2}  
                                    </p:column>  





                                </p:dataTable>  

                            </p:tab>  
                            <p:tab title="Patients" align="center">  


                                <p:dataTable var="patient" value="#{tableBean.patients}" rowKey="#{patient.id}" paginator="true" rows="10"  
                                             selection="#{tableBean.selectedPatient}" selectionMode="single" filteredValue="#{tableBean.filteredPatient}" id="patientsTable">  



                                    <f:facet name="header">  
                                        List of Patients  
                                    </f:facet>  

                                    <p:column headerText="ID" sortBy="#{patient.id}" filterBy="#{patient.id}" id="pid" style="text-align:center">  
                                        #{patient.id}  
                                    </p:column>  

                                    <p:column headerText="First Name" sortBy="#{patient.firstName}" filterBy="#{patient.firstName}" id="pfname" style="text-align:center">  
                                        #{patient.firstName}  
                                    </p:column>  

                                    <p:column headerText="Fathers Name" sortBy="#{patient.fatherName}" filterBy="#{patient.fatherName}" id="pfathername" style="text-align:center">  
                                        #{patient.fatherName}  
                                    </p:column>  

                                    <p:column headerText="Last Name" sortBy="#{patient.lastName}" filterBy="#{patient.lastName}" id="plname" style="text-align:center">  
                                        #{patient.lastName}  
                                    </p:column>  



                                    <p:column headerText="Actions" >  
                                        <p:commandButton id="editusers" value="View" 
                                                         action="#{tableBean.edituser()}"

                                                         type="submit"
                                                         >

                                            <f:param name="userID" value="#{patient.id}" />

                                        </p:commandButton>
                                    </p:column>  



                                </p:dataTable>  



                            </p:tab>  
                            <p:tab title="Schedules" align="center">  
                                <p:growl id="messages" showDetail="true" />  

                                <p:schedule value="#{scheduleController.eventModel}" style="width:750px" widgetVar="myschedule" align="center">  

                                    <p:ajax event="dateSelect" listener="#{scheduleController.onDateSelect}" update="eventDetails" oncomplete="eventDialog.show()" />  
                                    <p:ajax event="eventSelect" listener="#{scheduleController.onEventSelect}" update="eventDetails" oncomplete="eventDialog.show()" />  
                                    <p:ajax event="eventMove" listener="#{scheduleController.onEventMove}" update="messages" />  
                                    <p:ajax event="eventResize" listener="#{scheduleController.onEventResize}" update="messages" />  

                                </p:schedule>  

                                <p:dialog widgetVar="eventDialog" header="Event Details" showEffect="clip" hideEffect="clip">  
                                    <h:panelGrid id="eventDetails" columns="2">  
                                        <h:outputLabel for="title" value="Title:" />  
                                        <p:inputText id="title" value="#{scheduleController.event.title}" />  

                                        <h:outputLabel for="from" value="From:" />  
                                        <p:calendar id="from" value="#{scheduleController.event.startDate}" pattern="dd/MM/yyyy" />


                                        <h:outputLabel for="to" value="To:" />  
                                        <p:calendar id="to" value="#{scheduleController.event.endDate}" pattern="dd/MM/yyyy" />


                                        <h:outputLabel for="allDay" value="All Day:" />  
                                        <h:selectBooleanCheckbox id="allDay" value="#{scheduleController.event.allDay}" />  

                                        <p:commandButton type="reset" value="Reset" />  
                                        <p:commandButton value="Save" actionListener="#{scheduleController.addEvent}" oncomplete="myschedule.update();eventDialog.hide();"/>  
                                    </h:panelGrid>  
                                </p:dialog>   
                            </p:tab>  




                        </p:tabView>    
                    </p:layoutUnit>

                </p:layout>
            </h:form>
        </h:body>

    </f:view>
</html>

trunk/Portal/NephronWebPortal/web/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    
    xmlns:p="http://primefaces.org/ui">

     <div id="header-e1">
    <p:graphicImage value="images/logo4.jpg" />
</div>
<div id="header-e3">
    
</div>
<div id="header-e2">
    <p:commandLink id="Home" action="DashBoard.xhtml" style="color:#C30E4A;font-size:14px;margin-right:20px;" ajax="false">  
                            <h:outputText value="My Patients" />  
                        </p:commandLink>  
    

                        <p:commandLink id="logout" action="#{loginManager.logout}" style="color:#C30E4A;font-size:14px;margin-right:20px;" ajax="false">  
                            <h:outputText value="Logout" />  
                        </p:commandLink> 
</div>
    
    
    
    
</ui:composition>

trunk/Portal/NephronWebPortal/web/header_d.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    
    xmlns:p="http://primefaces.org/ui">

     <div id="header-e1">
    <p:graphicImage value="images/logo4.jpg" />
</div>
<div id="header-e3">
    
</div>
<div id="header-e2">
    

                        <p:commandLink id="logout" action="#{loginManager.logout}" style="color:#C30E4A;font-size:14px;margin-right:20px;" ajax="false">  
                            <h:outputText value="Logout" />  
                        </p:commandLink> 
</div>
    
    
    
    
</ui:composition>

trunk/Portal/NephronWebPortal/web/header_i.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    
    xmlns:p="http://primefaces.org/ui">

    <div id="header-e1">
    <p:graphicImage value="images/logo4.jpg" />
</div>
<div id="header-e3">
    
</div>
<div id="header-e2">
    
</div>
    
    


</ui:composition>

trunk/Portal/NephronWebPortal/web/menu_i.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    
    xmlns:p="http://primefaces.org/ui">

    <p:menu>
        <p:submenu label="Login">
            <p:menuitem value="Login" url="index.xhtml" />
        </p:submenu>
    </p:menu>
</ui:composition>